<?php
return array (
  'uname' => 
  array (
    'fieldid' => '312',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'uname',
    'name' => '姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'sex' => 
  array (
    'fieldid' => '313',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'sex',
    'name' => '性别',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'男|0
女|1\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'cols\' => \'5\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '男|0
女|1',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'hometel' => 
  array (
    'fieldid' => '314',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'hometel',
    'name' => '手机号码',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'zhuanye' => 
  array (
    'fieldid' => '315',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'zhuanye',
    'name' => '专业',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'汽车检测与运营工程师[技能+大专]|1
汽车检测与运营工程师[技能+中专]|2
汽车商务与管理[2+1大中专连读]|3
汽车检测与维修高级技师[实训+技能]|4
汽车4S维修高级技师[一年纯技能]|5
汽车4S维修高级技师[一年纯技能]|6
汽车维修与运营工程师[技能+中专]|7\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'cols\' => \'5\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '汽车检测与运营工程师[技能+大专]|1
汽车检测与运营工程师[技能+中专]|2
汽车商务与管理[2+1大中专连读]|3
汽车检测与维修高级技师[实训+技能]|4
汽车4S维修高级技师[一年纯技能]|5
汽车4S维修高级技师[一年纯技能]|6
汽车维修与运营工程师[技能+中专]|7',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'qq' => 
  array (
    'fieldid' => '316',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'qq',
    'name' => 'QQ',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'email' => 
  array (
    'fieldid' => '317',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'email',
    'name' => 'E-Mail',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'address' => 
  array (
    'fieldid' => '318',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'address',
    'name' => '家庭住址',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'beizhu' => 
  array (
    'fieldid' => '319',
    'modelid' => '21',
    'siteid' => '1',
    'field' => 'beizhu',
    'name' => '个人备注',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'100%\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>