<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `pd_category`;");
E_C("CREATE TABLE `pd_category` (
  `catid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `module` varchar(15) NOT NULL,
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `modelid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `parentid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `arrparentid` varchar(255) NOT NULL,
  `child` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `arrchildid` mediumtext NOT NULL,
  `catname` varchar(30) NOT NULL,
  `style` varchar(5) NOT NULL,
  `image` varchar(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `parentdir` varchar(100) NOT NULL,
  `catdir` varchar(30) NOT NULL,
  `url` varchar(100) NOT NULL,
  `items` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `setting` mediumtext NOT NULL,
  `listorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ismenu` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `sethtml` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `letter` varchar(30) NOT NULL,
  `usable_type` varchar(255) NOT NULL,
  PRIMARY KEY (`catid`),
  KEY `module` (`module`,`parentid`,`listorder`,`catid`),
  KEY `siteid` (`siteid`,`type`)
) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=utf8");
E_D("replace into `pd_category` values('1','1','content','1','0','0','0','1','1,15,16,17,7,25,18,19','学校概况','','','','','about','/html/about/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''1'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','1','1','0','xuexiaogaikuang','');");
E_D("replace into `pd_category` values('16','1','content','1','0','1','0,1','0','16','庞大荣誉','','','','about/','honor','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=16','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','2','1','0','pangdarongyu','');");
E_D("replace into `pd_category` values('17','1','content','1','0','1','0,1','0','17','领导关怀','','','','about/','care','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=17','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','3','1','0','lingdaoguanhuai','');");
E_D("replace into `pd_category` values('15','1','content','1','0','1','0,1','0','15','学校概况','','','','about/','xxgk','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=15','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','1','1','0','xuexiaogaikuang','');");
E_D("replace into `pd_category` values('6','1','content','0','12','0','0','0','6','专业设置','','','','','major','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=6','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','2','1','0','zhuanyeshezhi','');");
E_D("replace into `pd_category` values('7','1','content','1','0','1','0,1','0','7','就业分配','','','','about/','jyfp','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=7','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','4','1','0','jiuyefenpei','');");
E_D("replace into `pd_category` values('8','1','content','0','13','0','0','0','8','名师风采','','','','','teacher','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=8','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','4','1','0','mingshifengcai','');");
E_D("replace into `pd_category` values('9','1','content','0','1','0','0','0','9','院校合作','','','','','colleges','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=9','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','5','1','0','yuanxiaohezuo','');");
E_D("replace into `pd_category` values('10','1','content','0','1','0','0','0','10','校园环境','','','','','xyhj','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=10','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','6','1','0','xiaoyuanhuanjing','');");
E_D("replace into `pd_category` values('11','1','content','0','1','0','0','0','11','战略合作','','','','','zlhz','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=11','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','7','1','0','zhanluehezuo','');");
E_D("replace into `pd_category` values('12','1','content','0','1','0','0','0','12','证书查询','','','','','certificate','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=12','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','8','1','0','zhengshuchaxun','');");
E_D("replace into `pd_category` values('13','1','content','0','1','0','0','0','13','资料下载','','','','','download','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=13','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','9','1','0','ziliaoxiazai','');");
E_D("replace into `pd_category` values('14','1','content','0','1','0','0','0','14','网上报名','','','','','baoming','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=14','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','10','1','0','wangshangbaoming','');");
E_D("replace into `pd_category` values('18','1','content','1','0','1','0,1','0','18','庞大4S店图片','','','','about/','4s','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=18','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','6','1','0','pangda4sdiantupian','');");
E_D("replace into `pd_category` values('19','1','content','1','0','1','0,1','0','19','庞大汽车产业文化园','','','','about/','culture','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=19','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','7','1','0','pangdaqichechanyewenhuayuan','');");
E_D("replace into `pd_category` values('20','1','content','0','18','0','0','0','20','人才招聘','','','','','hr','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=20','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','11','0','0','rencaizhaopin','');");
E_D("replace into `pd_category` values('21','1','content','0','1','0','0','1','21,22,23,24','新闻动态','','','','','news','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=21','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','12','0','0','xinwendongtai','');");
E_D("replace into `pd_category` values('22','1','content','0','1','21','0,21','0','22','学校新闻','','','','news/','xxxw','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=22','200','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','1','1','0','xuexiaoxinwen','');");
E_D("replace into `pd_category` values('23','1','content','0','1','21','0,21','0','23','就业喜报','','','','news/','xibao','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=23','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','2','1','0','jiuyexibao','');");
E_D("replace into `pd_category` values('24','1','content','0','1','21','0,21','0','24','媒体报道','','','','news/','reports','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=24','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','3','1','0','meitibaodao','');");
E_D("replace into `pd_category` values('25','1','content','1','0','1','0,1','0','25','关于我们','','','','about/','gywm','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=25','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','5','1','0','guanyuwomen','');");
E_D("replace into `pd_category` values('26','1','content','0','15','0','0','1','26,27,28,29,30','开班信息','','','','','class','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=26','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','13','0','0','kaibanxinxi','');");
E_D("replace into `pd_category` values('27','1','content','0','15','26','0,26','0','27','奔驰订单班','','','','class/','benz','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=27','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','1','1','0','benchidingdanban','');");
E_D("replace into `pd_category` values('28','1','content','0','15','26','0,26','0','28','奥迪订单班','','','','class/','audi','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=28','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','2','1','0','aodidingdanban','');");
E_D("replace into `pd_category` values('29','1','content','0','15','26','0,26','0','29','斯巴鲁订单班','','','','class/','subaru','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=29','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','3','1','0','sibaludingdanban','');");
E_D("replace into `pd_category` values('30','1','content','0','15','26','0,26','0','30','商学院高级创业班','','','','class/','business','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=30','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','4','1','0','shangxueyuangaojichuangyeban','');");
E_D("replace into `pd_category` values('31','1','content','0','3','0','0','1','31,32,33,34,35','精彩图片','','','','','photo','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=31','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','14','0','0','jingcaitupian','');");
E_D("replace into `pd_category` values('32','1','content','0','3','31','0,31','0','32','学习环境','','','','photo/','xxhj','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=32','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','1','1','0','xuexihuanjing','');");
E_D("replace into `pd_category` values('33','1','content','0','3','31','0,31','0','33','生活环境','','','','photo/','shhj','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=33','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','2','1','0','shenghuohuanjing','');");
E_D("replace into `pd_category` values('34','1','content','0','3','31','0,31','0','34','校园活动','','','','photo/','xyhd','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=34','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','3','1','0','xiaoyuanhuodong','');");
E_D("replace into `pd_category` values('35','1','content','0','3','31','0,31','0','35','实训设备','','','','photo/','sxsb','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=35','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','4','1','0','shixunshebei','');");
E_D("replace into `pd_category` values('36','1','content','0','16','0','0','0','36','商学院视频','','','','','video','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=36','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category_video'',\n  ''list_template'' => ''list_video'',\n  ''show_template'' => ''show_video'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','15','0','0','shangxueyuanshipin','');");
E_D("replace into `pd_category` values('37','1','content','0','14','0','0','0','37','校友会','','','','','alumn','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=37','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','16','0','0','xiaoyouhui','');");
E_D("replace into `pd_category` values('38','1','content','0','19','0','0','0','38','合作企业','','','','','partners','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=38','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','17','0','0','hezuoqiye','');");
E_D("replace into `pd_category` values('39','1','content','0','20','0','0','0','39','就业明星','','','','','star','http://localhost.pangda.com/index.php?m=content&c=index&a=lists&catid=39','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''pangda'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','18','0','0','jiuyemingxing','');");

require("../../inc/footer.php");
?>