<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `pd_model_field`;");
E_C("CREATE TABLE `pd_model_field` (
  `fieldid` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `modelid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `field` varchar(20) NOT NULL,
  `name` varchar(30) NOT NULL,
  `tips` text NOT NULL,
  `css` varchar(30) NOT NULL,
  `minlength` int(10) unsigned NOT NULL DEFAULT '0',
  `maxlength` int(10) unsigned NOT NULL DEFAULT '0',
  `pattern` varchar(255) NOT NULL,
  `errortips` varchar(255) NOT NULL,
  `formtype` varchar(20) NOT NULL,
  `setting` mediumtext NOT NULL,
  `formattribute` varchar(255) NOT NULL,
  `unsetgroupids` varchar(255) NOT NULL,
  `unsetroleids` varchar(255) NOT NULL,
  `iscore` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `issystem` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `isunique` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `isbase` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `issearch` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `isadd` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `isfulltext` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `isposition` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `listorder` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `disabled` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `isomnipotent` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`fieldid`),
  KEY `modelid` (`modelid`,`disabled`),
  KEY `field` (`field`,`modelid`)
) ENGINE=MyISAM AUTO_INCREMENT=309 DEFAULT CHARSET=utf8");
E_D("replace into `pd_model_field` values('1','1','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('2','1','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('3','1','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('4','1','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('5','1','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('6','1','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','0','0');");
E_D("replace into `pd_model_field` values('7','1','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('8','1','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('9','1','1','voteid','添加投票','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''text\\\\'' name=\\\\''info[voteid]\\\\'' id=\\\\''voteid\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' size=\\\\''3\\\\''> \r\n<input type=\\\\''button\\\\'' value=\"选择已有投票\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=vote&c=vote&a=public_get_votelist&from_api=1\\\\'',\\\\''选择已有投票\\\\'')\" class=\"button\">\r\n<input type=\\\\''button\\\\'' value=\"新增投票\" onclick=\"omnipotent(\\\\''addvote\\\\'',\\\\''?m=vote&c=vote&a=add&from_api=1\\\\'',\\\\''添加投票\\\\'',0)\" class=\"button\">'',\n  ''fieldtype'' => ''mediumint'',\n  ''minnumber'' => ''1'',\n)','','','','0','0','0','1','0','0','1','0','21','0','0');");
E_D("replace into `pd_model_field` values('10','1','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('11','1','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('12','1','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('13','1','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('14','1','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('15','1','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('16','1','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('17','1','1','groupids_view','阅读权限','','','0','0','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('18','1','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('19','1','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('20','1','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''1'',\n  ''filtertype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('21','1','1','copyfrom','来源','','','0','100','','','copyfrom','array (\n  ''defaultvalue'' => '''',\n)','','','','0','0','0','1','0','1','0','0','8','0','0');");
E_D("replace into `pd_model_field` values('80','1','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('22','2','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('23','2','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','1','0');");
E_D("replace into `pd_model_field` values('24','2','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('25','2','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('26','2','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','0','0');");
E_D("replace into `pd_model_field` values('27','2','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('28','2','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n  ''height'' => '''',\n  ''disabled_page'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('29','2','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('30','2','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('31','2','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','1','0');");
E_D("replace into `pd_model_field` values('32','2','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('33','2','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('34','2','1','groupids_view','阅读权限','','','0','0','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('35','2','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('36','2','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('37','2','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('38','2','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''1'',\n  ''filtertype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('39','2','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('40','2','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('41','2','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('42','2','1','downfiles','本地下载','','','0','0','','','downfiles','array (\n  ''upload_allowext'' => ''rar|zip'',\n  ''isselectimage'' => ''0'',\n  ''upload_number'' => ''10'',\n  ''downloadlink'' => ''1'',\n  ''downloadtype'' => ''1'',\n)','','','','0','0','0','1','0','1','0','0','8','0','0');");
E_D("replace into `pd_model_field` values('43','2','1','downfile','镜像下载','','','0','0','','','downfile','array (\n  ''downloadlink'' => ''1'',\n  ''downloadtype'' => ''1'',\n  ''upload_allowext'' => ''rar|zip'',\n  ''isselectimage'' => ''0'',\n  ''upload_number'' => ''1'',\n)','','','','0','0','0','1','0','1','0','0','9','0','0');");
E_D("replace into `pd_model_field` values('44','2','1','systems','软件平台','<select name=''selectSystem'' onchange=\"ChangeInput(this,document.myform.systems,''/'')\">\r\n	<option value=''WinXP''>WinXP</option>\r\n	<option value=''Vista''>Windows 7</option>\r\n	<option value=''Win2000''>Win2000</option>\r\n	<option value=''Win2003''>Win2003</option>\r\n	<option value=''Unix''>Unix</option>\r\n	<option value=''Linux''>Linux</option>\r\n	<option value=''MacOS''>MacOS</option>\r\n</select>','','0','100','','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => ''Win2000/WinXP/Win2003'',\n  ''ispassword'' => ''0'',\n)','','','','0','1','0','1','0','1','1','0','14','0','0');");
E_D("replace into `pd_model_field` values('45','2','1','copytype','软件授权形式','','','0','15','','','box','array (\n  ''options'' => ''免费版|免费版\r\n共享版|共享版\r\n试用版|试用版\r\n演示版|演示版\r\n注册版|注册版\r\n破解版|破解版\r\n零售版|零售版\r\nOEM版|OEM版'',\n  ''boxtype'' => ''select'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n  ''cols'' => ''5'',\n  ''width'' => ''80'',\n  ''size'' => ''1'',\n  ''default_select_value'' => ''免费版'',\n)','','','','0','1','0','1','0','1','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('46','2','1','language','软件语言','','','0','16','','','box','array (\n  ''options'' => ''英文|英文\r\n简体中文|简体中文\r\n繁体中文|繁体中文\r\n简繁中文|简繁中文\r\n多国语言|多国语言\r\n其他语言|其他语言'',\n  ''boxtype'' => ''select'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n  ''cols'' => ''5'',\n  ''width'' => ''80'',\n  ''size'' => ''1'',\n  ''default_select_value'' => ''简体中文'',\n)','','','','0','1','0','1','0','1','0','0','13','0','0');");
E_D("replace into `pd_model_field` values('47','2','1','classtype','软件类型','','','0','20','','','box','array (\n  ''options'' => ''国产软件|国产软件\r\n国外软件|国外软件\r\n汉化补丁|汉化补丁\r\n程序源码|程序源码\r\n其他|其他'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n  ''cols'' => ''5'',\n  ''width'' => ''80'',\n  ''size'' => ''1'',\n  ''default_select_value'' => ''国产软件'',\n)','','','','0','1','0','1','0','1','0','0','17','0','0');");
E_D("replace into `pd_model_field` values('48','2','1','version','版本号','','','0','20','','','text','array (\n  ''size'' => ''10'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','1','0','0','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('49','2','1','filesize','文件大小','','','0','10','','','text','array (\n  ''size'' => ''10'',\n  ''defaultvalue'' => ''未知'',\n  ''ispassword'' => ''0'',\n)','','','','0','1','0','0','0','1','1','0','14','0','0');");
E_D("replace into `pd_model_field` values('50','2','1','stars','评分等级','','','0','20','','','box','array (\n  ''options'' => ''★☆☆☆☆|★☆☆☆☆\r\n★★☆☆☆|★★☆☆☆\r\n★★★☆☆|★★★☆☆\r\n★★★★☆|★★★★☆\r\n★★★★★|★★★★★'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n  ''cols'' => ''5'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''default_select_value'' => ''★★★☆☆'',\n)','','','','0','1','0','1','0','1','0','0','17','0','0');");
E_D("replace into `pd_model_field` values('51','3','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''1'',\n  ''filtertype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('52','3','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('53','3','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('54','3','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('55','3','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('56','3','1','groupids_view','阅读权限','','','0','0','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('57','3','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('58','3','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('59','3','1','relation','相关组图','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('60','3','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('61','3','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','0','999999','','','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n  ''height'' => '''',\n  ''disabled_page'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('62','3','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('63','3','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','0','0');");
E_D("replace into `pd_model_field` values('64','3','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('65','3','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('66','3','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('67','3','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('68','3','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('69','3','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('70','3','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('71','3','1','pictureurls','组图','','','0','0','','','images','array (\n  ''upload_allowext'' => ''gif|jpg|jpeg|png|bmp'',\n  ''isselectimage'' => ''1'',\n  ''upload_number'' => ''50'',\n)','','','','0','0','0','1','0','1','0','0','15','0','0');");
E_D("replace into `pd_model_field` values('72','3','1','copyfrom','来源','','','0','0','','','copyfrom','array (\n  ''defaultvalue'' => '''',\n)','','','','0','0','0','1','0','1','0','0','8','0','0');");
E_D("replace into `pd_model_field` values('73','1','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','0','0','1','0','0','30','0','0');");
E_D("replace into `pd_model_field` values('74','2','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','0','0','1','0','0','30','0','0');");
E_D("replace into `pd_model_field` values('75','3','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','0','0','1','0','0','30','0','0');");
E_D("replace into `pd_model_field` values('83','10','1','birthday','生日','','','0','0','','生日格式错误','datetime','array (\n  ''fieldtype'' => ''date'',\n  ''format'' => ''Y-m-d'',\n  ''defaulttype'' => ''0'',\n)','','','','0','0','0','0','0','1','1','0','0','0','0');");
E_D("replace into `pd_model_field` values('84','11','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('85','11','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('86','11','1','title','标题','','inputtitle','1','80','','请输入标题','title','array (\n)','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('87','11','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\n  ''size'' => ''100'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('88','11','1','description','摘要','','','0','255','','','textarea','array (\n  ''width'' => ''98'',\n  ''height'' => ''46'',\n  ''defaultvalue'' => '''',\n  ''enablehtml'' => ''0'',\n)','','','','0','1','0','1','0','1','1','1','10','0','0');");
E_D("replace into `pd_model_field` values('89','11','1','updatetime','更新时间','','','0','0','','','datetime','array (\n  ''dateformat'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''1'',\n  ''defaultvalue'' => '''',\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('90','11','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','0','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n  ''height'' => '''',\n  ''disabled_page'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('91','11','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('92','11','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('93','11','1','pages','分页方式','','','0','0','','','pages','array (\n)','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('94','11','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('95','11','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('96','11','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('97','11','1','url','URL','','','0','100','','','text','array (\n)','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('98','11','1','listorder','排序','','','0','6','','','number','array (\n)','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('99','11','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('100','11','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('101','11','1','status','状态','','','0','2','','','box','array (\n)','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('102','11','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('103','11','1','username','用户名','','','0','20','','','text','array (\n)','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('104','11','1','islink','转向链接','','','0','0','','','islink','array (\n)','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('105','11','1','video','视频上传','','','0','0','','','video','array (\n  ''upload_allowext'' => ''flv|rm|mp4|rmv'',\n)','','','','0','0','0','1','0','1','0','0','8','0','0');");
E_D("replace into `pd_model_field` values('106','11','1','vision','画质','','','0','0','','','box','array (\n  ''options'' => ''高清|1\r\n普通|2'',\n  ''boxtype'' => ''select'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''80'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''0'',\n  ''outputtype'' => ''1'',\n  ''filtertype'' => ''1'',\n)','','','','0','1','0','1','0','1','0','0','9','1','0');");
E_D("replace into `pd_model_field` values('107','11','1','video_category','视频分类','','','0','0','','','box','array (\n  ''options'' => ''喜剧|1\r\n爱情|2\r\n科幻|3\r\n剧情|4\r\n动作|5\r\n伦理|6'',\n  ''boxtype'' => ''select'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''80'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''1'',\n  ''filtertype'' => ''1'',\n)','','','','0','1','0','1','0','1','0','0','9','1','0');");
E_D("replace into `pd_model_field` values('108','12','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('109','12','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('110','12','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('111','12','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','5','1','0');");
E_D("replace into `pd_model_field` values('112','12','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('113','12','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('114','12','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('115','12','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('116','12','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('117','12','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('118','12','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('119','12','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('120','12','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('121','12','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('122','12','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('123','12','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('124','12','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('125','12','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('126','12','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('127','12','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('128','12','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('129','13','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('130','13','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('131','13','1','title','教师姓名','','inputtitle','1','20','','','title','','','','','0','1','0','1','1','1','1','1','3','0','0');");
E_D("replace into `pd_model_field` values('132','13','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');");
E_D("replace into `pd_model_field` values('133','13','1','description','专业特长','','','0','255','','','textarea','array (\n  ''width'' => ''98'',\n  ''height'' => ''46'',\n  ''defaultvalue'' => '''',\n  ''enablehtml'' => ''0'',\n)','','','','0','1','0','1','0','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('134','13','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('135','13','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('136','13','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('137','13','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('138','13','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('139','13','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('140','13','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('141','13','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('142','13','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('143','13','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('144','13','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('145','13','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('146','13','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('147','13','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('148','13','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('149','13','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('150','12','1','zsdx','招生对象','','','0','0','','','textarea','array (\n  ''width'' => ''100'',\n  ''height'' => ''46'',\n  ''defaultvalue'' => '''',\n  ''enablehtml'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','6','0','0');");
E_D("replace into `pd_model_field` values('151','12','1','zyts','专业特色','','','0','0','','','textarea','array (\n  ''width'' => ''100'',\n  ''height'' => ''46'',\n  ''defaultvalue'' => '''',\n  ''enablehtml'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('152','12','1','qq','在线咨询','请输入在线QQ号码','','0','0','/^[0-9]{5,20}\$/','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','8','0','0');");
E_D("replace into `pd_model_field` values('153','14','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('154','14','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('155','14','1','title','姓名','','inputtitle','1','80','','请输入姓名','title','','','','','0','1','0','1','1','1','1','1','3','0','0');");
E_D("replace into `pd_model_field` values('156','14','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');");
E_D("replace into `pd_model_field` values('157','14','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('158','14','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('159','14','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('160','14','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('161','14','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('162','14','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('163','14','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('164','14','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('165','14','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('166','14','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('167','14','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('168','14','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('169','14','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('170','14','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('171','14','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('172','14','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('173','14','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('174','14','1','major','专业','','','0','0','','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','4','0','0');");
E_D("replace into `pd_model_field` values('175','14','1','enddate','毕业时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''date'',\n  ''format'' => ''Y-m-d'',\n  ''defaulttype'' => ''0'',\n)','','','','0','0','0','1','0','1','0','0','5','0','0');");
E_D("replace into `pd_model_field` values('176','14','1','jydw','单位','','','0','0','','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','6','0','0');");
E_D("replace into `pd_model_field` values('177','15','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('178','15','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('179','15','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','3','0','0');");
E_D("replace into `pd_model_field` values('180','15','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');");
E_D("replace into `pd_model_field` values('181','15','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('182','15','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('183','15','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('184','15','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('185','15','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('186','15','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('187','15','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('188','15','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('189','15','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('190','15','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('191','15','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('192','15','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('193','15','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('194','15','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('195','15','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('196','15','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('197','15','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('198','15','1','leftnum','剩余人数','请输入剩余人数','','0','0','/^[0-9-]+\$/','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','5','0','0');");
E_D("replace into `pd_model_field` values('199','15','1','totalnum','招生总数','请输入招生总数','','0','0','/^[0-9-]+\$/','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','4','0','0');");
E_D("replace into `pd_model_field` values('200','16','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('201','16','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('202','16','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','3','0','0');");
E_D("replace into `pd_model_field` values('203','16','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');");
E_D("replace into `pd_model_field` values('204','16','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('205','16','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('206','16','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','0','0');");
E_D("replace into `pd_model_field` values('207','16','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('208','16','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('209','16','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('210','16','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('211','16','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('212','16','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('213','16','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('214','16','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('215','16','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('216','16','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('217','16','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('218','16','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('219','16','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('220','16','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('221','16','1','videourl','视频地址','请输入有效的视频地址','','0','0','/^http:\\\\/\\\\//','','text','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''ispassword'' => ''0'',\n)','','','','0','0','0','1','0','1','1','0','4','0','0');");
E_D("replace into `pd_model_field` values('222','17','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('223','17','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('224','17','1','title','在线QQ','','inputtitle','1','20','/^[0-9]{5,20}\$/','','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('225','17','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');");
E_D("replace into `pd_model_field` values('226','17','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('227','17','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('228','17','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','1','0');");
E_D("replace into `pd_model_field` values('229','17','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('230','17','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('231','17','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('232','17','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('233','17','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('234','17','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('235','17','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('236','17','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('237','17','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('238','17','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('239','17','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('240','17','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('241','17','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('242','17','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('244','18','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('245','18','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('246','18','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','3','0','0');");
E_D("replace into `pd_model_field` values('247','18','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('248','18','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('249','18','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('250','18','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','1','0');");
E_D("replace into `pd_model_field` values('251','18','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('252','18','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('253','18','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('254','18','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('255','18','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('256','18','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('257','18','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('258','18','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('259','18','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('260','18','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('261','18','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('262','18','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('263','18','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('264','18','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('265','18','1','gwzz','岗位职责','','','0','0','','','editor','array (\n  ''toolbar'' => ''basic'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''0'',\n  ''replacenum'' => ''1'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''0'',\n  ''height'' => ''200'',\n)','','','','0','0','0','1','0','1','1','0','5','0','0');");
E_D("replace into `pd_model_field` values('266','18','1','rzyq','任职要求','','','0','0','','','editor','array (\n  ''toolbar'' => ''basic'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''0'',\n  ''replacenum'' => ''1'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''0'',\n  ''height'' => ''200'',\n)','','','','0','0','0','1','0','1','1','0','4','0','0');");
E_D("replace into `pd_model_field` values('267','19','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('268','19','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('269','19','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('270','19','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','0','0');");
E_D("replace into `pd_model_field` values('271','19','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','0','0');");
E_D("replace into `pd_model_field` values('272','19','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('273','19','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','1','0');");
E_D("replace into `pd_model_field` values('274','19','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('275','19','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('276','19','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('277','19','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('278','19','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('279','19','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('280','19','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('281','19','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('282','19','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('283','19','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('284','19','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('285','19','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('286','19','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('287','19','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");
E_D("replace into `pd_model_field` values('288','20','1','catid','栏目','','','1','6','/^[0-9]{1,6}\$/','请选择栏目','catid','array (\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','1','0','1','1','1','0','0','1','0','0');");
E_D("replace into `pd_model_field` values('289','20','1','typeid','类别','','','0','0','','','typeid','array (\n  ''minnumber'' => '''',\n  ''defaultvalue'' => '''',\n)','','','','0','1','0','1','1','1','0','0','2','0','0');");
E_D("replace into `pd_model_field` values('290','20','1','title','标题','','inputtitle','1','80','','请输入标题','title','','','','','0','1','0','1','1','1','1','1','4','0','0');");
E_D("replace into `pd_model_field` values('291','20','1','keywords','关键词','多关键词之间用空格或者“,”隔开','','0','40','','','keyword','array (\r\n  ''size'' => ''100'',\r\n  ''defaultvalue'' => '''',\r\n)','','-99','-99','0','1','0','1','1','1','1','0','7','1','0');");
E_D("replace into `pd_model_field` values('292','20','1','description','摘要','','','0','255','','','textarea','array (\r\n  ''width'' => ''98'',\r\n  ''height'' => ''46'',\r\n  ''defaultvalue'' => '''',\r\n  ''enablehtml'' => ''0'',\r\n)','','','','0','1','0','1','0','1','1','1','10','1','0');");
E_D("replace into `pd_model_field` values('293','20','1','updatetime','更新时间','','','0','0','','','datetime','array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)','','','','1','1','0','1','0','0','0','0','12','0','0');");
E_D("replace into `pd_model_field` values('294','20','1','content','内容','<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=''checkbox'' name=''auto_thumb'' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>','','1','999999','','内容不能为空','editor','array (\n  ''toolbar'' => ''full'',\n  ''defaultvalue'' => '''',\n  ''enablekeylink'' => ''1'',\n  ''replacenum'' => ''2'',\n  ''link_mode'' => ''0'',\n  ''enablesaveimage'' => ''1'',\n)','','','','0','0','0','1','0','1','1','0','13','1','0');");
E_D("replace into `pd_model_field` values('295','20','1','thumb','缩略图','','','0','100','','','image','array (\n  ''size'' => ''50'',\n  ''defaultvalue'' => '''',\n  ''show_type'' => ''1'',\n  ''upload_maxsize'' => ''1024'',\n  ''upload_allowext'' => ''jpg|jpeg|gif|png|bmp'',\n  ''watermark'' => ''0'',\n  ''isselectimage'' => ''1'',\n  ''images_width'' => '''',\n  ''images_height'' => '''',\n)','','','','0','1','0','0','0','1','0','1','14','0','0');");
E_D("replace into `pd_model_field` values('296','20','1','relation','相关文章','','','0','0','','','omnipotent','array (\n  ''formtext'' => ''<input type=\\\\''hidden\\\\'' name=\\\\''info[relation]\\\\'' id=\\\\''relation\\\\'' value=\\\\''{FIELD_VALUE}\\\\'' style=\\\\''50\\\\'' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\\''button\\\\'' value=\"添加相关\" onclick=\"omnipotent(\\\\''selectid\\\\'',\\\\''?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\\'',\\\\''添加相关文章\\\\'',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\\''button\\\\'' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>'',\n  ''fieldtype'' => ''varchar'',\n  ''minnumber'' => ''1'',\n)','','2,6,4,5,1,17,18,7','','0','0','0','0','0','0','1','0','15','0','0');");
E_D("replace into `pd_model_field` values('297','20','1','pages','分页方式','','','0','0','','','pages','','','-99','-99','0','0','0','1','0','0','0','0','16','0','0');");
E_D("replace into `pd_model_field` values('298','20','1','inputtime','发布时间','','','0','0','','','datetime','array (\n  ''fieldtype'' => ''int'',\n  ''format'' => ''Y-m-d H:i:s'',\n  ''defaulttype'' => ''0'',\n)','','','','0','1','0','0','0','0','0','1','17','0','0');");
E_D("replace into `pd_model_field` values('299','20','1','posids','推荐位','','','0','0','','','posid','array (\n  ''cols'' => ''4'',\n  ''width'' => ''125'',\n)','','','','0','1','0','1','0','0','0','0','18','0','0');");
E_D("replace into `pd_model_field` values('300','20','1','groupids_view','阅读权限','','','0','100','','','groupid','array (\n  ''groupids'' => '''',\n)','','','','0','0','0','1','0','0','0','0','19','0','0');");
E_D("replace into `pd_model_field` values('301','20','1','url','URL','','','0','100','','','text','','','','','1','1','0','1','0','0','0','0','50','0','0');");
E_D("replace into `pd_model_field` values('302','20','1','listorder','排序','','','0','6','','','number','','','','','1','1','0','1','0','0','0','0','51','0','0');");
E_D("replace into `pd_model_field` values('303','20','1','template','内容页模板','','','0','30','','','template','array (\n  ''size'' => '''',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','53','0','0');");
E_D("replace into `pd_model_field` values('304','20','1','allow_comment','允许评论','','','0','0','','','box','array (\n  ''options'' => ''允许评论|1\r\n不允许评论|0'',\n  ''boxtype'' => ''radio'',\n  ''fieldtype'' => ''tinyint'',\n  ''minnumber'' => ''1'',\n  ''width'' => ''88'',\n  ''size'' => ''1'',\n  ''defaultvalue'' => ''1'',\n  ''outputtype'' => ''0'',\n)','','','','0','0','0','0','0','0','0','0','54','0','0');");
E_D("replace into `pd_model_field` values('305','20','1','status','状态','','','0','2','','','box','','','','','1','1','0','1','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('306','20','1','readpoint','阅读收费','','','0','5','','','readpoint','array (\n  ''minnumber'' => ''1'',\n  ''maxnumber'' => ''99999'',\n  ''decimaldigits'' => ''0'',\n  ''defaultvalue'' => '''',\n)','','-99','-99','0','0','0','0','0','0','0','0','55','0','0');");
E_D("replace into `pd_model_field` values('307','20','1','username','用户名','','','0','20','','','text','','','','','1','1','0','1','0','0','0','0','98','0','0');");
E_D("replace into `pd_model_field` values('308','20','1','islink','转向链接','','','0','0','','','islink','','','','','0','1','0','1','0','1','0','0','20','0','0');");

require("../../inc/footer.php");
?>